### ISSUE TITLE
outdated lib Newtonsoft

### ISSUE THREAD

**Issue by Augustukas** [dmitry-brazhenko/SharpToken#10]
Need to update Newtonsoft to 13.0.1
cause current versions have issues.
https://security.snyk.io/vuln/SNYK-DOTNET-NEWTONSOFTJSON-2774678?_gl=1%2a1ovg81w%2a_ga%2aMjU2MTczODMuMTY4MTI5OTE2OA..%2a_ga_X9SH3KP7B4%2aMTY4ODAyOTk2NS40LjEuMTY4ODAyOTk2NS4wLjAuMA..

**Comment by dmitry-brazhenko** [comment]
Hello
Thanks a lot for your messages. 
Looks like newtonsoft.json is not referenced in Sharptoken lib. 

Thanks 

<img width="740" alt="2023-06-30_11-49-31" src="https://github.com/dmitry-brazhenko/SharpToken/assets/61410067/bd8d4b64-c0aa-4f4f-b28c-856046a9a8bc">
