### ISSUE TITLE
Performance compared to TiktokenSharp, Tokenizer

### ISSUE THREAD

**Issue by lofcz** [dmitry-brazhenko/SharpToken#2]
SharpToken seems to be actively maintained, we are evaluating a possible switch from [TiktokenSharp](https://github.com/aiqinxuancai/TiktokenSharp). I'm interested in whether the performance is the same or how SharpToken performs compared to TiktokenSharp and [Tokenizer](https://github.com/microsoft/Tokenizer). Quickly gazing through the codebase, core BPE is not taking advantage of SSE, AVX2/512, or other SIMD implementations (like arm neon) yet.

Do you know if any of this is planned?

**Comment by dmitry-brazhenko** [comment]
Hi @lofcz !

Thanks for reaching out!

I planned to implement some performance improvements and compare it with other libs. But not yet. If you have any ideas of improvements, please let me know and I will use them for improvement :)

**Comment by vwilson** [comment]
I have a branch using RegexOptions.Compiled in several places. I think this will improve performance in long-lived instances of the GptEncoding class, but it actually runs the extant unit tests slightly slower than the main branch. I'm still playing with it and have several MB of public domain novels to crunch. Maybe a consumer-level option to use RegexOptions.Compiled in a couple places at least would be called for. I will let you know when I have finished.

**Comment by Anurag-RTS** [comment]
Ran a quick encode benchmark with 5500 words input:

```
BenchmarkDotNet=v0.13.5, OS=Windows 10 (10.0.19045.3086/22H2/2022Update)
AMD Ryzen 7 1700, 1 CPU, 16 logical and 8 physical cores
.NET SDK=7.0.203
  [Host]     : .NET 7.0.5 (7.0.523.17405), X64 RyuJIT AVX2
  DefaultJob : .NET 7.0.5 (7.0.523.17405), X64 RyuJIT AVX2
```


|           Method |       Mean |    Error |   StdDev |
|----------------- |-----------:|---------:|---------:|
|  TokenizerEncode |   450.5 us |  4.61 us |  4.31 us |
|   TikTokenEncode |   504.1 us |  3.82 us |  2.99 us |
| SharpTokenEncode | 2,704.0 us | 21.60 us | 20.20 us |

**Comment by dmitry-brazhenko** [comment]
Hey @UX-Ayoma !

THanks a lot for sharing!
I will explore what can be improved in the lib. I would say that there are lot of stuff to be done. 

I started with some easy and added some optimisation for Decoding (https://github.com/dmitry-brazhenko/SharpToken/pull/9). 
I will explore and implement fixes for Encoding as well.

**Comment by dmitry-brazhenko** [comment]
Fixed encoding here: [PR #11](https://github.com/dmitry-brazhenko/SharpToken/pull/11). 

Will update with benchmarks and more improvements later.

**Comment by dmitry-brazhenko** [comment]
Here is an updated benchmarks that I calclulated. Will check what can be improved 


|                     Method |  Categories |                Data |           Mean |         Median | Ratio | 
|--------------------------- |------------ |-------------------- |---------------:|---------------:|------:|
|   SharpTokenV1_0_28_Encode |      Encode | 1. (...)57. [19866] | 3,374,121.7 ns | 3,227,934.8 ns |  1.00 | 
| TiktokenSharpV1_0_5_Encode |      Encode | 1. (...)57. [19866] | 3,415,080.4 ns | 3,399,812.1 ns |  1.11 |
|  TokenizerLibV1_3_2_Encode |      Encode | 1. (...)57. [19866] | 2,060,565.1 ns | 2,027,039.6 ns |  0.63 | 
|            Tiktoken_Encode |      Encode | 1. (...)57. [19866] |   921,540.6 ns |   895,316.2 ns |  0.28 |

**Comment by dmitry-brazhenko** [comment]
There is a new version that has a significant improvements thanks to @r-Larch https://github.com/dmitry-brazhenko/SharpToken/commit/086544dcccfd36562a6eac2d5d1f603db9255925
