### ISSUE TITLE
Implement MODEL_PREFIX_FOR_ENCODING

### ISSUE THREAD

**Issue by ian-cameron** [dmitry-brazhenko/SharpToken#21]
Would you be willing to implement support for model prefix to encoding, such as https://github.com/openai/tiktoken/blob/5d970c1100d3210b42497203d6b5c1e30cfda6cb/tiktoken/model.py#L63-L69 in TikToken for model names like gpt-3.5-turbo-0401, etc?  Or will you take a PR for it?

Then it would support this kind of model name, currently it gives {"Could not automatically map gpt-3.5-turbo-0301 to a tokenizer. Please use GetEncoding to explicitly get the tokenizer you expect."}

We could probably add it to Model.cs with a similar approach when a model is not found in the dictionary, fall back to seeing the model starts with a key from a model prefix dictionary.

**Comment by dmitry-brazhenko** [comment]
Hello @ian-cameron !
Could you create a PR please? :) 

I will have a look and improve it if necessary

**Comment by ian-cameron** [comment]
Thanks for the lib, and quick merge!
