### ISSUE TITLE
New embedding models not recognized

### ISSUE THREAD

**Issue by thomasdc** [dmitry-brazhenko/SharpToken#27]
The library fails to recognize the encoding for the new embedding models: `text-embedding-3-large` and `text-embedding-3-small`

See https://platform.openai.com/docs/guides/embeddings/embedding-models

**Comment by dmitry-brazhenko** [comment]
Hello @thomasdc !

Thanks for raising an issue. 

As far as i understand, embeddings algorithms are caclulated on OpenAI side. This algorithm (most likely some neural network) is not publicly available

**Comment by thomasdc** [comment]
According to the mentioned docs it uses `cl100k_base`.

**Comment by dmitry-brazhenko** [comment]
@thomasdc could you share please expected behavior? 
Would you like to have smth like ?
`var encoding = GptEncoding.GetEncodingForEmbeddingModel("text-embedding-3-large");`

**Comment by thomasdc** [comment]
`GptEncoding.GetEncodingForModel("text-embedding-ada-002");` was working fine, but throws for `text-embedding-3-large`

**Comment by dmitry-brazhenko** [comment]
Ok, understood. I will add this functionality today. 
Thanks for sharing

**Comment by dmitry-brazhenko** [comment]
https://github.com/dmitry-brazhenko/SharpToken/pulls

**Comment by dmitry-brazhenko** [comment]
Thanks for your feddback. I just introduced this change. Should work in the newer version (1.2.15) once it is available in nuget. Probably in 1-2 hours

**Comment by thomasdc** [comment]
Ok thanks, can you add `small` as well?

**Comment by dmitry-brazhenko** [comment]
@thomasdc  could you share the full name please? I will add it

**Comment by thomasdc** [comment]
See my first comment.

**Comment by dmitry-brazhenko** [comment]
Sorry, I missed it. 
https://github.com/dmitry-brazhenko/SharpToken/pull/29
it should become available in v.1.2.16
Please let me know if smth does not work
