### ISSUE TITLE
Add Microsoft.SourceLink.GitHub to publish repo info/commit to nuget.org

### ISSUE THREAD

**Issue by kzu** [dmitry-brazhenko/SharpToken#3]
Right now, there's no repo info in nuget.org about the project.

Would be nice to get that as well as commit info. The above package can provide that.

Just set the following project properties:

```xml
    <PackageProjectUrl>[if different from repo ]</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
```

**Comment by dmitry-brazhenko** [comment]
Hey @kzu !

Thanks for reaching out. I added it here: https://github.com/dmitry-brazhenko/SharpToken/commit/42d9dc1221ab2887d19f0b1f5ff5b89af5d4aad4

Hope it will work :)
