### ISSUE TITLE
GptEncoding thread-safe?

### ISSUE THREAD

**Issue by omri-suissa-clearmash** [dmitry-brazhenko/SharpToken#30]
Is the SharpToken GptEncoding thread-safe, or should we create a new instance for every request?

**Comment by dmitry-brazhenko** [comment]
Hello!
I would say that it should be thread-safe. I will double check that. 

Could you try this as well please? If you observe any problems, please let me know

**Comment by omri-suissa-clearmash** [comment]
I saw Dictionary usage in the code. It is ok as long as they are created and modified only in the contracture. Otherwise, it is not thread-safe.

**Comment by vwilson** [comment]
This library is threadsafe.  I have submitted a PR with an additional unit test that would seem to prove this. https://github.com/dmitry-brazhenko/SharpToken/pull/31

**Comment by dmitry-brazhenko** [comment]
https://github.com/dmitry-brazhenko/SharpToken/pull/31
