### ISSUE TITLE
Missing model name for 3.5 turbo Azure Deployment model

### ISSUE THREAD

**Issue by bsstahl** [dmitry-brazhenko/SharpToken#6]
Nice job on this, thanks for doing it!

The one thing I noticed is that the Azure deployment model name for the gpt-35-turbo model was not included in [Model.cs](https://github.com/dmitry-brazhenko/SharpToken/blob/main/SharpToken/Lib/Model.cs#L12). It looks like it was added later in TikToken. I have an easy-enough work-around by testing for the value in my code and making the switch, but I suspect that you'll want to get that fixed before there is truly widespread adoption of this port.

Again, thanks for putting this together. I think it will be valuable.

*Edited to make it clear that the name I'm referring to was added after-the-fact in TikToken*.

**Comment by bsstahl** [comment]
FYI - It looks like TikToken added it as an Azure deployment name:

```
    "gpt-3.5-turbo": "cl100k_base",
    "gpt-35-turbo": "cl100k_base",  # Azure deployment name
```

**Comment by winzig** [comment]
The official name of the model from OpenAI's API does include the period, e.g.:

* `gpt-3.5-turbo`
* `gpt-3.5-turbo-0301`
* `gpt-3.5-turbo-16k-0613`
* etc...

If you hit `https://api.openai.com/v1/models` (when authenticated) you can see all available models.

**Comment by bsstahl** [comment]
@winzig Is there a reason the Azure deployment name would be included in TikToken but not here? I thought this was intended as a port of that library.

**Comment by bsstahl** [comment]
I've edited the original comment so it is clear that the Azure Deployment name was added after the original creation of TikToken.

**Comment by dmitry-brazhenko** [comment]
We can add gpt-35-turbo as well. I do not see any problems with it
